version: '3.1'

services:
  snm:
    image: johannesschafer/simple-network-monitor
    container_name: simple-network-monitor
    restart: always
    ports:
     - 8080:8080
    #environment:
    #  HOSTS_FILE: file:/myHosts.json
    #  SETTINGS_FILE: file:/mySettings.json
    #  COMMANDS_FILE: file:/myCommands.json
    #volumes:
    #  - ./myHosts.json:/myHosts.json
    #  - ./mySettings.json:/mySettings.json
    #  - ./myCommands.json:/myCommands.json
